name: Publicar Aula no GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: raphateixeira/.github/.github/workflows/quarto-publish.yml@main
    with:
      needs_python: true
      python_packages: "pandas numpy scipy matplotlib jupyter pyyaml"
      needs_pdf2svg: true
      needs_tinytex: true
      tinytex_packages: "pgf standalone xcolor"
      output_dir: "docs"
